### ISSUE TITLE
Configurable invitees for support rooms.

### ISSUE THREAD

**Issue by squahtx** [matrix-org/conference-bot#76]
Proposed config:
```yaml
supportRooms:
  speakers:
    alias: "#speakers:example.org"
    roomPrefixes: ["D.", "M.", "K.", "L."]
    roles: ["speaker"]
  specialInterest:
    alias: "#stands:example.org"
    roomPrefixes: ["S."]
    roles: ["speaker", "host", "coordinator"]
  coordinators:
    alias: "#coordinators:example.org"
    roomPrefixes: ["D."]
    roles: ["coordinator"]
```
