### ISSUE TITLE
Cleaner conference space config?

### ISSUE THREAD

**Issue by squahtx** [matrix-org/conference-bot#84]
Currently the conference space is defined in the config as follows:
```yaml
conference:
  supportRooms:
    speakers: "#speakers:example.org"
    specialInterest: "#stands:example.org"
    coordinators: "#devroom-managers:example.org"

  prefixes:
    # The prefixes for the rooms listed in the pentabarf definition which
    # describe the rooms that are 'auditorium' rooms. The prefixes will be
    # trimmed when naming the room (unless an override is present).
    auditoriumRooms: ["D.", "M.", "K.", "L."]

    # The prefixes for the rooms listed in the pentabarf definition which
    # describe the rooms that are 'special interest' rooms. The prefixes will
    # be trimmed when naming the room (unless an override is present).
    interestRooms: ["S.", "B.", "I."]

    # The alias suffixes to apply for certain prefixes of rooms
    suffixes:
      "K.": "-keynotes"
      "D.": "-devroom"
      "S.": "-stand"

    # The display name suffixes to apply for certain prefixes of rooms
    displayNameSuffixes:
      "D.": " devroom"
      "S.": " stand"

  # The subspaces to create under the main conference space
  subspaces:
    infodesk:
      displayName: Infodesk
      alias: infodesk
      prefixes: ["I."]
    main-tracks:
      displayName: Main Tracks
      alias: main-tracks
      prefixes: ["K.", "M.", "L."]
    devrooms:
      displayName: Devrooms
      alias: devrooms
      prefixes: ["D."]
    stands:
      displayName: Stands
      alias: stands
      prefixes: ["S."]
```

This is a bit messy:
 * the config for auditoriums and interest rooms lives all over the place
 * support rooms are implicitly added to the top-level conference space
 * only one level of subspaces can be defined
 * the ordering of rooms within a subspace can't be defined
 * and we don't support pulling in non-bot created rooms like FOSDEM's `#cafe` or `#food-trucks`.

We could replace the above config with something like:
```yaml
conference:
  # ...
  space-children:
    - type: "interests"
      prefixes: ["I."]
    - type: room
      room: "#cafe:fosdem.org"
    - "#food-trucks:fosdem.org" # implicit type: room
    - type: "support"
      alias: "#speakers:example.org"
      # other support room config
      # see https://github.com/matrix-org/conference-bot/issues/76
    - type: "space"
      displayName: Main Tracks
      alias: main-tracks
      children:
        - type: "auditoriums"
          prefixes: ["K."]
          aliasSuffix: "-keynotes"
        - type: "auditoriums"
          prefixes: ["M.", "L."]
    - type: "space"
      displayName: Devrooms
      alias: devrooms
      children:
        - type: "auditoriums"
          prefixes: ["D."]
          aliasSuffix: "-devroom"
          displayNameSuffix: " devroom"
    - type: "space"
      displayName: Stands
      alias: stands
      children:
        - type: "interests"
          prefixes: ["S."]
          aliasSuffix: "-stand"
          displayNameSuffix: " stand"
```

Each (sub)space has a list describing its children. Each child can be:
* Another subspace
* A single pre-existing room to be added
* A series of auditoriums
* A series of interest rooms
* A support room
Space children can be assigned an order key based on their position within the list, eg. "1", "2", "3-devroom1", "3-devroom2".

The prefixes and suffixes for auditoriums and stands would now live inside the appropriate definition within the space hierarchy.
